version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk22
    commands:
      - echo "Installing dependencies..."
      - yum install -y zip unzip

  pre_build:
    commands:
      - echo "Preparing for build..."
      - mvn --version
      - java -version

  build:
    commands:
      - echo "Building the application..."
      - mvn clean package

  post_build:
    commands:
      - echo "Creating deployment package..."
      - mkdir -p deployment/{scripts,config}
      - cp target/*.jar deployment/
      - cp src/main/resources/application.yml deployment/config/
      - cp src/main/resources/scripts/* deployment/scripts/
      - cp src/main/resources/appspec.yaml deployment/
      - chmod +x deployment/scripts/*
      - cd deployment && zip -r ../content-service.zip .
      - cd ..
      - echo "Deployment package created:- content-service.zip"

artifacts:
  files:
    - content-service.zip
  discard-paths: yes
    
