version: 0.0
os: linux
files:
  - source: /
    destination: /opt/content-service
    overwrite: yes
permissions:
  - object: /opt/content-service
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  Install:
    - location: scripts/install.sh
      timeout: 120
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 120
      runas: root
    - location: scripts/stop_application.sh
      timeout: 120
      runas: ec2-user
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 120
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 120
      runas: ec2-user
  ValidateService:
    - location: scripts/health_check.sh
      timeout: 120
      runas: ec2-user