version: 0.0
os: linux
files:
  - source: /
    destination: /opt/content-service
permissions:
  - object: /opt/content-service
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
  - object: /opt/content-service/scripts
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 120
      runas: root
  ValidateService:
    - location: scripts/health_check.sh
      timeout: 120
      runas: root