version: 0.0
os: linux
files:
  - source: /target/content-service-0.0.1-SNAPSHOT.jar
    destination: /opt/content-service/
  - source: /config/application.yaml
    destination: /opt/content-service/config/
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 120
      runas: root
  ValidateService:
    - location: scripts/health_check.sh
      timeout: 120
      runas: root